---
- name: Begin
  hosts: 127.0.0.1
  become: yes

  roles:

    - role: add_template
      when: action == 'add'
    
    - role: remove_template
      when: action == 'remove'

    - role: refresh_all
      when: action == 'refresh_all'
  
  tasks:
    - name: Reload service nginx
      service:
        name: httpd
        state: reloaded

  vars:
    conf_path: "/tmp/nginx/records"
    ssl_path: "/tmp/nginx/ssl"
#    cert_path: "/etc/nginx/config.d/ssl/{{ domain }}/ssl.crt"
#    key_path: "/etc/nginx/config.d/ssl/{{ domain }}/ssl.key"
    records_file: "/tmp/all"


