---
- name: 'verify conf folder'
  file: 
    path: "{{ conf_path }}"
    state: directory
#    owner: nginx
#    group: nginx
    mode: 0644

- name: 'verify conf folder'
  file: 
    path: "{{ ssl_path }}"
    state: directory
#    owner: nginx
#    group: nginx
    mode: 0644
    
- name: 'Default type'
  import_tasks: default.yml
  when: cert is undefined

- name: 'SSL type'
  import_tasks: ssl.yml
  when: cert is defined
