---
- name: 'Parse file'
  set_fact:
    content: "{{ lookup('file', records_file).split('\n') }}"

# - debug:
#     msg: "{{ content }}"

- name: 'Clear all configs'
  file:
    state: absent
    path: "{{ conf_path }}/"

- name: 'Clear all ssl'
  file:
    state: absent
    path: "{{ ssl_path }}/"

- name: 'Restore configs folder'
  file:
    state: directory
    path: "{{ conf_path }}/"

- name: 'Restore ssl folder'
  file:
    state: directory
    path: "{{ ssl_path }}/"

- name: 'Call add_tempalte'
  include_role:
    name: add_template
  vars:
    domain: "{{ item.split(' ')[0] }}"
    cert: "{{ item.split(' ')[1] }}"
    key: "{{ item.split(' ')[2] }}"
  loop: "{{ content }}"


